### ISSUE TITLE
ps2.0 dataset or the PSV dataset sharing

### ISSUE THREAD

**Issue by kangting521** [weili1457355863/VPS-Net#1]
Ps2.0 dataset and the PSV dataset can't be downloaded from the Internet, can you share it?

**Comment by weili1457355863** [comment]
Ok. The Baidunet download link for ps 2.0 is : https://pan.baidu.com/s/1AQMsh_dwGNcS1sQw2v9yzw 
    Extraction code：wix5.
For PSV: https://pan.baidu.com/s/1dWpC1UKPhex-LBFv2nfKSw 
Extraction code：wk0e

**Comment by kangting521** [comment]
Thank you very much

**Comment by kangting521** [comment]
Hello, the two files you sent are exactly the same, only PSV, can you send ps2.0 dataset again？
Can you share your own annotation data about Parking Slot Occupancy Classification?
