### ISSUE TITLE
How to train on my own dataset?

### ISSUE THREAD

**Issue by AndresHuang** [weili1457355863/VPS-Net#3]
Hi there, this network works really well on PS2.0 dataset!
Could you please give a guidance on how to train my own dataset and add related code to this repo？
Thank you very much!

**Comment by weili1457355863** [comment]
Sorry. Now we can only provide the test code. If you want to train your own dataset, you can refer to the training methods of yolov3 and the training methods of commonly used classification networks.

**Comment by AndresHuang** [comment]
@weili1457355863 
Okay,thanks for your contribution to this field. Hope to see the training code in the near future.
