### ISSUE TITLE
最后得到的结果txt文件是如何表示的？

### ISSUE THREAD

**Issue by FireflyInwater** [weili1457355863/VPS-Net#4]
论文所做的工作很不错！但是看完之后我没有明白最后得到的结果是如何表示的（是在什么坐标系下表示的结果？）txt文件中的四个点是？

**Comment by weili1457355863** [comment]
谢谢您的认可。生成的txt文件不是直接的4个点，而是车位的角度，两个可见顶点的坐标（图像坐标系下）。车位的另外两个坐标可以根据车位的几何关系得到。具体的内容可以参考论文和对应的程序。

**Comment by FireflyInwater** [comment]
> 谢谢您的认可。生成的txt文件不是直接的4个点，而是车位的角度，两个可见顶点的坐标（图像坐标系下）。车位的另外两个坐标可以根据车位的几何关系得到。具体的内容可以参考论文和对应的程序。
谢谢！明白了！
