### ISSUE TITLE
PS2.0数据集标注信息转化

### ISSUE THREAD

**Issue by AndresHuang** [weili1457355863/VPS-Net#5]
您好，感谢您的项目，请问您是否可以提供方法把PS2.0数据集的标注信息转换成更方便YOLOv3训练的四种类别目标框信息呢？因为我真的很喜欢您的这个项目，想用python在自己的数据集上训练一下试试。COCO或者VOC格式的都可以。训练的过程我自己参考通用YOLOV3的就可以。感谢~ @weili1457355863

**Comment by weili1457355863** [comment]
我把数据集标注转化的程序给您，你按照您的需求进行对应的修改吧。
link:链接：https://pan.baidu.com/s/1K6bOWI3dSAdmEPEOaruvTg 
提取码：3apw

**Comment by AndresHuang** [comment]
非常感谢您，谢谢




| |
黄翊轩
|
|
邮箱：huangyixuan1997@126.com
|
在2020年06月10日 18:26，weili1457355863 写道：

我把数据集标注转化的程序给您，你按照您的需求进行对应的修改吧。
link:链接：https://pan.baidu.com/s/1K6bOWI3dSAdmEPEOaruvTg
提取码：3apw

**Comment by AndresHuang** [comment]
非常感谢您，谢谢～

**Comment by XiaoJiNu** [comment]
@您好，转换代码已经失效了，请问能否再发一次

**Comment by guo-pu** [comment]
@weili1457355863 您好，这个项目很赞，请问能把数据集标注转化的程序发我一下吗，感谢~

**Comment by rwb1123** [comment]
@weili1457355863  您好，转换代码已经失效了，请问能否再发一次

**Comment by Dizzy-TCP** [comment]
> 您好，感谢您的项目，请问您是否可以提供方法把PS2.0数据集的标注信息转换成更方便YOLOv3训练的四种类别目标框信息呢？因为我真的很喜欢您的这个项目，想用python在自己的数据集上训练一下试试。COCO或者VOC格式的都可以。训练的过程我自己参考通用YOLOV3的就可以。感谢~ @weili1457355863

请问您转换文件还在吗？作者之前发的链接已经失效了。

**Comment by Heikozhu** [comment]
您好，标签转化文件已经失效了，请问您能再发一下吗

**Comment by bing0426** [comment]
> 您好，感谢您的项目，请问您是否可以提供方法把PS2.0数据集的标注信息转换成更方便YOLOv3训练的四种类别目标框信息呢？因为我真的很喜欢您的这个项目，想用python在自己的数据集上训练一下试试。COCO或者VOC格式的都可以。训练的过程我自己参考通用YOLOV3的就可以。感谢~ [@weili1457355863](https://github.com/weili1457355863)

你好，请问您是否下载了标签转换文件，如果有是否可以分享？谢谢
