### ISSUE TITLE
测试中发现了文章采用方法的不足

### ISSUE THREAD

**Issue by FireflyInwater** [weili1457355863/VPS-Net#6]
文章是采用IOU来确定车位bbox的方向的，但正因为如此，当车横在车位线上时（数据集中有一些这种场景，如outdoor-slanted中04、06.jpg等场景），这种方法就出现了问题，使得结果的方向刚好相反（与正确结果刚好对称）。请问您觉得可以怎么解决？

**Comment by weili1457355863** [comment]
针对这个问题，目前我是设计了一个新的车位检测器。具体的做法是将车位建模为一个有方向的线，直接回归出线的一些特性，从而获得整个车位。

**Comment by chengshuai** [comment]
> 针对这个问题，目前我是设计了一个新的车位检测器。具体的做法是将车位建模为一个有方向的线，直接回归出线的一些特性，从而获得整个车位。

Hell weal,

你的新方法有相关论文吗？
谢谢
